MAX_ZIP_SIZE_MB = 100
MAX_SINGLE_FILE_MB = 20
SUPPORTED_ESSAY_EXTENSIONS = {'.docx', '.pdf', '.txt'}
SUPPORTED_RUBRIC_EXTENSIONS = {'.docx', '.pdf', '.txt'}
GRADING_TIMEOUT_SECONDS = 120
MAX_RETRY_ATTEMPTS = 3
